name: Tests

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
  push:
    tags:
      - v*.*.*

jobs:
  l1-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: L1 Action
        uses: product-os/l1-transformer@make-github-action
