name: Bootstrap transformer-builder

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
  push:
    tags:
      - v*.*.*

jobs:
  l1-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Transform
        env:
          REGISTRY_USERNAME: ${{ github.event.pull_request.user.login }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash bootstrap.sh
